### ISSUE TITLE
Cannot manage Task Manager on Windows 11

### ISSUE THREAD

**Issue by iholston** [LGUG2Z/komorebi-application-specific-configuration#109]
Adding [float_rules](https://lgug2z.github.io/komorebi/common-workflows/force-manage-windows.html) to my komorebi.json does not seem to work. Additionally, I've removed task manager rules from the applications.yaml and it still does not manage it. Even adding 'komorebic.exe manage' to a hotkey and trying to press it on task manager does not work.

**Comment by LGUG2Z** [comment]
This is a Windows security "feature"; applications run with regular privileges (ie. komorebi) cannot manipulate the Task Manager.
