### ISSUE TITLE
Unity Editor breaks when using transparency

### ISSUE THREAD

**Issue by davor-skontra** [LGUG2Z/komorebi-application-specific-configuration#110]
Hello! 

Unity Editor seems to be breaking with transparency enabled. I tried across two different machines and two major versions of Unity (6 and 2022). The exe file seems to be always titled `Unity.exe` so that might be a good strategy for setting to ignore transparency. 

Btw, I can create a PR if you'd like me to.

**Comment by LGUG2Z** [comment]
Hi!

Sounds good to me, I'm glad that we can express transparency ignore directives in the v2 schema now 🎉 

Please go ahead with the PR!

**Comment by davor-skontra** [comment]
Allrighty here is a [PR](https://github.com/LGUG2Z/komorebi-application-specific-configuration/pull/111).

I added an additional rule for Unity (reasoning in PR) 

Its still a very tiny one but but sure if adding that to the same PR that was cool, so please do let me know.

And yeah, the transparency ignore directives came in handy 💪
