### ISSUE TITLE
AutoCAD and Civil3D popup windows being tiled instead of floating

### ISSUE THREAD

**Issue by Lucho32-byte** [LGUG2Z/komorebi-application-specific-configuration#126]
So, recently I noticed some windows like calc and export are being tiled by komorebi in programs know as acad.exe like AutoCAD and Civil3D:

![imagen](https://github.com/user-attachments/assets/c12176ef-5f3a-4439-a50d-893fadab7e16)
![imagen](https://github.com/user-attachments/assets/2ffeeee5-2491-4080-ac74-839a02fa17bb)

This may be a headache since its recising the whole program just for opening a casual popup window. So I identify the class of the window and added the following rule to the ``applications.json'':
```diff
  "AutoDesk AutoCAD Suite": {
    "ignore": [
      [
        {
          "kind": "Class",
          "id": "Afx:",
          "matching_strategy": "Contains"
        },
        {
          "kind": "Exe",
          "id": "acad.exe",
          "matching_strategy": "Equals"
        }
      ],
      [
        {
          "kind": "Class",
          "id": "HwndWrapper[DefaultDomain",
          "matching_strategy": "StartsWith"
        },
        {
          "kind": "Exe",
          "id": "acad.exe",
          "matching_strategy": "Equals"
        }
-      ]
+      ],
+      [
+        {
+          "kind": "Class",
+          "id": "WindowsForms10.Window",
+          "matching_strategy": "StartsWith"
+        },
+        {
+          "kind": "Exe",
+          "id": "acad.exe",
+          "matching_strategy": "Equals"
+        }
+      ]
+    ]
  },

```

So far, the problem is solved:
![imagen](https://github.com/user-attachments/assets/d37c4b74-a8cb-445d-bc56-1fb2534bbe66)
![imagen](https://github.com/user-attachments/assets/e4c4a7a8-a71e-42d4-aafa-9af7b88ec9df)

**Comment by LGUG2Z** [comment]
Seems like a great rule addition which will help the onboarding for AutoCAD users who want to try komorebi, thanks for this contribution! Please go ahead and create a PR for this.

**Comment by Lucho32-byte** [comment]
No problem. I've just added a PR for the  applications.json file.
