### ISSUE TITLE
Add GIMP rules for floating windows

### ISSUE THREAD

**Issue by Lucho32-byte** [LGUG2Z/komorebi-application-specific-configuration#132]
There were no rules in `applications.json` for the `gimp-[version number].exe` executable for some basic floating windows such as:

New File
![imagen](https://github.com/user-attachments/assets/38a07455-6b23-4bba-8248-29759cd4ca11)

Preferences
![imagen](https://github.com/user-attachments/assets/0217decc-90e5-445a-8769-5818e5591b6c)

Input Devices
![imagen](https://github.com/user-attachments/assets/bc33dd46-6c56-4caf-b10c-0e18534c993d)

and many more...

Basically every window which title doesn't:
- Contains "GNU" (main page when the program's opened)
- Ends with "GIMP" (a file or project opened -since it follows the "Descriptive Title Format convention"- and main page in some languages)

So I added this to my `applications.json`:
```json
  "GIMP" : {
    "floating" : [
      [
        {
          "kind": "Exe",
          "id": "gimp",
          "matching_strategy": "StartsWith"
        },
        {
          "kind": "Title",
          "id": "GNU",
          "matching_strategy": "DoesNotContain"
        },
        {
          "kind": "Title",
          "id": "GIMP",
          "matching_strategy": "DoesNotEndWith"

        }
      ]
    ]
  },
```
(I could rely only in the `Title` because `Class` names were all the same: `gdkWindowToplevel` 🫠)

So, the floating windows now behave properly:

New File
![imagen](https://github.com/user-attachments/assets/b44d2576-819f-4bb0-ae48-9de36c0a1933)

Preferences
![imagen](https://github.com/user-attachments/assets/18bfce93-5be6-4aa7-8519-dad4bbf1497a)

Input Devices
![imagen](https://github.com/user-attachments/assets/ec569209-83b0-4463-b687-4ea6c33fcf6a)

**Comment by LGUG2Z** [comment]
This is really cool! Thanks for doing the investigation 🙏

Feel free to open a PR for this now

**Comment by Lucho32-byte** [comment]
Neat 😃. Done #133
