### ISSUE TITLE
Add manage rule for Tabby

### ISSUE THREAD

**Issue by TheLastZombie** [LGUG2Z/komorebi-application-specific-configuration#135]
[Tabby](https://tabby.sh/), a terminal emulator, seems to not be managed by Komorebi by default. It uses a generic window class (`Chrome_WidgetWin_1`, i. e. Electron):

![](https://github.com/user-attachments/assets/8772190b-0f14-4170-a5b6-8cb94d4cc3f7)

But the following works just fine:

```JSON
"manage_rules": [
  {
    "kind": "Exe",
    "id": "Tabby.exe",
    "matching_strategy": "Equals"
  }
]
```

**Comment by LGUG2Z** [comment]
Let's make this a composite rule which matches on the mixture of exe + class - you can go ahead and open the PR 🤞
