### ISSUE TITLE
Todoist, Obsidian, RSS Guard

### ISSUE THREAD

**Issue by mudnug** [LGUG2Z/komorebi-application-specific-configuration#141]
I upgraded komorebi 0.1.31 a few days ago and switched from applications.yaml to the latest applications.json which seems to be missing a lot of rules I would need to add for Todoist, Obsidian (with tray plugin), RSS Guard and perhaps other apps.

I'm just wanting to know if it was expected that the update would have broken many apps that go 'to tray.'

I haven't tried reverting to see if that resolves issues.

**Comment by mudnug** [comment]
I'm not Following this project closely enough to know whether the configuration is being adequately maintained but I can tell that the supposed new JSON file is missing an entry for todoist so reverting to the yaml does improve things

https://github.com/LGUG2Z/komorebi-application-specific-configuration/blob/master/applications.json
https://github.com/LGUG2Z/komorebi-application-specific-configuration/blob/master/applications.yaml

**Comment by LGUG2Z** [comment]
Please open a PR for any rules you find missing 🤞

**Comment by mudnug** [comment]
I have 2 thoughts about that

1) It feels like that process needs to be automated. (The process of comparing these two files and finding missing rules if the files are being edited independently)

2) The latest update has really set me back and hasn't fixed the one bug I had been seeing so I don't know if there is an easy way to revert, but I would prefer to do that over all the work of trying to figure out what is causing the apps that minimize to the tray to be an annoyance now.

**Comment by mudnug** [comment]
I uninstalled 1.31 and reinstalled 1.29 and that put me back in business much more quickly.

**Comment by LGUG2Z** [comment]
No new submissions are being accepted to the YAML file as the readme clarifies, and every non-empty rule was automatically migrated. I use two of the apps you mentioned, minimizing to tray without issue with the automatically migrated JSON file.

Hard to diagnose this further without legwork on your end, so I'm closing this issue as a wontdo.

**Comment by LGUG2Z** [comment]
For future readers, these are the empty rules in the YAML file which were previously ignored entirely by komorebi, and were subsequently ignored by the automated migration to the v2 format:

https://github.com/LGUG2Z/komorebi-application-specific-configuration/blob/a5d32fbe567575e77b53b9bf6511152f9e80572a/applications.yaml#L850

https://github.com/LGUG2Z/komorebi-application-specific-configuration/blob/a5d32fbe567575e77b53b9bf6511152f9e80572a/applications.yaml#L1577
