### ISSUE TITLE
mpv doesn't tile/stays floating (on purpose?)

### ISSUE THREAD

**Issue by Carl-Robert** [LGUG2Z/komorebi-application-specific-configuration#38]
I saw `mpv` is already added to the application specific configuration (actually it seems the PR adding mpv and mpv.net is partly reverted, because I see no mpv in my applications.yaml), so not sure if others deem this as the right way to handle it. For me I'd very much prefer it to be tiled normally.

If it is done on purpose, I petition to revert that.

**Comment by sitiom** [comment]
The mpv and mpv.net rules work for me. Did you try testing it first without a config? If you have a borderless config, we can't add a rule for that as Windows like those are a trouble to manage, and it's non-default behavior anyway, so that should be up to the user to add via the `overrides.yaml`.
