### ISSUE TITLE
Steam: popup window not filtered

### ISSUE THREAD

**Issue by starise** [LGUG2Z/komorebi-application-specific-configuration#88]
I'm quite new to komorebi so I apologize if I'm wrong or missing something. Fwiu this part of the file should filter out some "Steam" windows, I suppose popups looking the id `vguiPopupWindow`.

https://github.com/LGUG2Z/komorebi-application-specific-configuration/blob/b7d1da162f70aff37b77ebc9375d78c6be3c051a/applications.yaml#L1088-L1092

This isn't happening to me: right clicking on Steam's system tray icon, I see a giant window managed by komorebi. I'm not sure how/where I can find the Class.id specified: `vguiPopupWindow`, but I suppose with AHK spy, because looking at the popup with it I found this:

![ahkspy](https://github.com/LGUG2Z/komorebi-application-specific-configuration/assets/2684482/2bbd1df8-55d7-4edf-9e61-f02a842301ef)

That's the same id of the "Steam Beta" filter (nb: I'm not using the beta). Also, the popup window looks like it has the same id of the main application window.

https://github.com/LGUG2Z/komorebi-application-specific-configuration/blob/b7d1da162f70aff37b77ebc9375d78c6be3c051a/applications.yaml#L1093-L1103

Not sure how to proceed from here. Thanks to #56 I quite understood `matching_strategy`, but still not sure about `options` available and on what `float_identifiers` does exactly.

**Comment by LGUG2Z** [comment]
I've been playing around with this a bit, and the following composite float rule seems sensible to me:

```json
  "float_rules": [
    [
      {
        "kind": "Exe",
        "id": "steamwebhelper.exe",
        "matching_strategy": "Equals"
      },
      {
        "kind": "Title",
        "id": "Steam",
        "matching_strategy": "DoesNotEqual",
      }
    ]
  ],
```

**Comment by LGUG2Z** [comment]
Added here: https://github.com/LGUG2Z/komorebi-application-specific-configuration/commit/7acc4f6408101ddd97f7119f48d74d8ad5b5e2b2
