### ISSUE TITLE
First time Komorebi user

### ISSUE THREAD

**Issue by rwjack** [LGUG2Z/komorebi-application-specific-configuration#89]
How tf does applications.yaml work?

For example, I don't want explorer.exe to be tiled. The syntax is too confusing and I can't find anything in the docs: https://lgug2z.github.io/komorebi/example-configurations.html#application-specific-configuration

**Comment by LGUG2Z** [comment]
Welcome!

Explorer will continue to be managed-by-default (this repo is primarily for defining default behaviours), but if you would like to ignore Explorer windows on your machine you can add a rule to your komorebi.json file: https://lgug2z.github.io/komorebi/common-workflows/ignore-windows.html

**Comment by rwjack** [comment]
Thanks! I'll take a look over there.
