### ISSUE TITLE
Emacs running through WSL is ignored by komorebi

### ISSUE THREAD

**Issue by charleslowell-valstro** [LGUG2Z/komorebi-application-specific-configuration#93]
Oddly, running emacs as a native app seems to work just fine. Is this a problem with all WSL apps, or just emacs?

**Comment by sitiom** [comment]
Yes, the problem is from WSL:
- https://github.com/LGUG2Z/komorebi/issues/216
- https://github.com/LGUG2Z/komorebi/issues/285
