### ISSUE TITLE
1Password not tiled

### ISSUE THREAD

**Issue by tsuphona** [LGUG2Z/komorebi-application-specific-configuration#99]
Hi I notice that 1Password is included in app specific configurations, but for some reason, it doesn't get tiled. Also Windows task manager doesn't get tiled either, I'm using windows 11.

**Comment by urob** [comment]
Most people prefer 1Password and TaskManager not to be tiled. This is why the app specific rules *exempt* them from getting tiled by default.

**Comment by tsuphona** [comment]
Thank for the reply @urob , how could I adapt the app specific config to tile apps that are not tiled by default.

**Comment by bedge** [comment]
Same question, I'd prefer 1password be tiled as well.

**Comment by LGUG2Z** [comment]
https://lgug2z.github.io/komorebi/common-workflows/force-manage-windows.html

If anyone wants to override apps that are set to float here, the mechanism to use is manage rules in komorebi.json
